spring:
  datasource:
    url: jdbc:h2:mem:identity_test;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

app:
  jwt:
    # 64+ chars so HS512 key length is valid
    secret: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
    expiration: 60000
